function Task = g_Constraint(in1)
%G_CONSTRAINT
%    TASK = G_CONSTRAINT(IN1)

<<<<<<< Updated upstream
%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    31-Mar-2021 12:05:44
=======
%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-Apr-2021 17:36:53
>>>>>>> Stashed changes

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
<<<<<<< Updated upstream
t2 = q1+q2+q3;
t3 = cos(t2);
t4 = q1+q2;
t5 = cos(t4);
t6 = cos(q1);
Task = [t3./2.0+t5./2.0+t6./2.0;t3+t5+t6];
=======
t2 = cos(q1);
t3 = q1+q2;
t4 = cos(t3);
t5 = q3+t3;
t6 = cos(t5);
Task = [t2./2.0+t4./2.0+t6./2.0;t2+t4+t6];
>>>>>>> Stashed changes
