function TaskJacobian = g_Constraint_Jacobian(in1)
%G_CONSTRAINT_JACOBIAN
%    TASKJACOBIAN = G_CONSTRAINT_JACOBIAN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    15-Jun-2021 18:21:41

TaskJacobian = reshape([1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0],[2,4]);
