function Task = g_Constraint(in1)
%G_CONSTRAINT
%    TASK = G_CONSTRAINT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Jun-2021 15:03:44

q1 = in1(1,:);
q2 = in1(2,:);
Task = [q1;q2];
