function c = g_dynamics_c(in1,in2)
%G_DYNAMICS_C
%    C = G_DYNAMICS_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Jun-2021 15:03:42

q3 = in1(3,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
v4 = in2(4,:);
t2 = sin(q3);
t3 = v3.^2;
c = [v1.*(-6.0./5.0)-t2.*t3.*(3.0./4.0);v2.*(-6.0./5.0)-t3.*cos(q3).*(3.0./4.0)-9.8e+1./5.0;t2.*(1.47e+2./2.0e+1)-v3.*(6.0./5.0);v4.*(-6.0./5.0)];
