function H = g_dynamics_H(in1)
%G_DYNAMICS_H
%    H = G_DYNAMICS_H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Jun-2021 15:03:42

q3 = in1(3,:);
t2 = cos(q3);
t3 = sin(q3);
t4 = t2.*(3.0./4.0);
t5 = t3.*(3.0./4.0);
t6 = -t5;
H = reshape([2.0,0.0,t4,0.0,0.0,2.0,t6,0.0,t4,t6,5.5e+1./4.8e+1,5.0./1.2e+1,0.0,0.0,5.0./1.2e+1,5.0./1.2e+1],[4,4]);
