function c = g_dynamics_c(in1,in2)
%G_DYNAMICS_C
%    C = G_DYNAMICS_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    15-Jun-2021 18:21:41

q3 = in1(3,:);
v3 = in2(3,:);
t2 = sin(q3);
t3 = v3.^2;
c = [t2.*t3.*(-2.09978e-1);t3.*cos(q3).*2.09978e-1+6.566;t2.*2.0577844;1.5e-4];
