function T = g_dynamics_T(in1)
%G_DYNAMICS_T
%    T = G_DYNAMICS_T(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    15-Jun-2021 18:21:41

T = [0.0;0.0;0.0;6.1e+1./1.0e+3];
