function H = g_dynamics_H(in1)
%G_DYNAMICS_H
%    H = G_DYNAMICS_H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    15-Jun-2021 18:21:41

q3 = in1(3,:);
t2 = cos(q3);
t3 = sin(q3);
t4 = t2.*2.09978e-1;
t5 = t3.*2.09978e-1;
H = reshape([6.7e+1./1.0e+2,0.0,t4,0.0,0.0,6.7e+1./1.0e+2,t5,0.0,t4,t5,7.12991052e-2,-1.7e-3,0.0,0.0,-1.7e-3,1.7e-3],[4,4]);
