function B = g_linearization_B(in1,in2,in3)
%G_LINEARIZATION_B
%    B = G_LINEARIZATION_B(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-Apr-2021 15:49:00

iH1_1 = in3(1);
iH1_2 = in3(3);
iH2_1 = in3(2);
iH2_2 = in3(4);
B = reshape([0.0,0.0,iH1_1,iH2_1,0.0,0.0,iH1_2,iH2_2],[4,2]);
