function T = g_dynamics_T(in1)
%G_DYNAMICS_T
%    T = G_DYNAMICS_T(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Jun-2021 15:51:43

T = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],[3,3]);
