function B = g_linearization_B(in1,in2,in3)
%G_LINEARIZATION_B
%    B = G_LINEARIZATION_B(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    15-Jun-2021 18:21:43

iM1_4 = in3(19);
iM2_4 = in3(20);
iM3_4 = in3(21);
iM4_4 = in3(22);
B = [0.0;0.0;0.0;0.0;iM1_4.*(6.1e+1./1.0e+3);iM2_4.*(6.1e+1./1.0e+3);iM3_4.*(6.1e+1./1.0e+3);iM4_4.*(6.1e+1./1.0e+3)];
