function Task = g_InverseKinematics_Task(in1)
%G_INVERSEKINEMATICS_TASK
%    TASK = G_INVERSEKINEMATICS_TASK(IN1)

<<<<<<< Updated upstream
%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    31-Mar-2021 12:05:44
=======
%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-Apr-2021 17:36:54
>>>>>>> Stashed changes

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
<<<<<<< Updated upstream
Task = [q1;q2;cos(q1+q2+q3)./2.0+cos(q1+q2)./2.0+cos(q1)./2.0];
=======
t2 = q1+q2;
Task = [q1;q2;cos(q3+t2)./2.0+cos(q1)./2.0+cos(t2)./2.0];
>>>>>>> Stashed changes
