function B = g_linearization_B(in1,in2,in3)
%G_LINEARIZATION_B
%    B = G_LINEARIZATION_B(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Jun-2021 15:03:44

iH1_4 = in3(13);
iH2_4 = in3(14);
iH3_4 = in3(15);
iH4_4 = in3(16);
B = [0.0;0.0;0.0;0.0;iH1_4;iH2_4;iH3_4;iH4_4];
